#! /bin/bash

CURRENT_DIRECTORY="`dirname $0`"
cd "$CURRENT_DIRECTORY"

# Make sure build can see this file
touch "$CURRENT_DIRECTORY/Resources/InfoPlist.h"

# Initial Commit
git init
echo "Resources/InfoPlist.h
initial-git-commit" > .gitignore
git add .gitignore
git add .
echo "Resources/InfoPlist.h" > .gitignore
git add .gitignore
git commit -am "Initial commit"

# Commit to the repository
git remote add origin git@github.com:rocket0423/travisexample.git
git push --all
git branch --set-upstream master origin/master

rm -f "$CURRENT_DIRECTORY/initial-git-commit"
