#! /bin/bash

CURRENT_DIRECTORY="`dirname $0`"
cd "$CURRENT_DIRECTORY"

mkdir -p "$CURRENT_DIRECTORY/Classes/Additions"
mkdir -p "$CURRENT_DIRECTORY/Classes/Cells"
mkdir -p "$CURRENT_DIRECTORY/Classes/Generated"
mkdir -p "$CURRENT_DIRECTORY/Classes/Generated/Catalogs"
mkdir -p "$CURRENT_DIRECTORY/Classes/Generated/Fonts"
mkdir -p "$CURRENT_DIRECTORY/Classes/Generated/Identifiers"
mkdir -p "$CURRENT_DIRECTORY/Classes/Helpers"
mkdir -p "$CURRENT_DIRECTORY/Classes/View Controllers"
mkdir -p "$CURRENT_DIRECTORY/Classes/Views"
mkdir -p "$CURRENT_DIRECTORY/Classes/Model Objects"
mkdir -p "$CURRENT_DIRECTORY/External Frameworks"
mkdir -p "$CURRENT_DIRECTORY/Resources"
rmdir -p "$CURRENT_DIRECTORY/`basename ${CURRENT_DIRECTORY}`"

# This makes mogenerator and inital-git-commit a unix executable script
chmod +x "$CURRENT_DIRECTORY/mogenerator-script"
chmod +x "$CURRENT_DIRECTORY/initial-git-commit"

# Do Initial Run Of Generated Items
GENERATED_PATH="$CURRENT_DIRECTORY/Classes/Generated"
"$CURRENT_DIRECTORY/codegenutils/objc-assetgen" -f "$CURRENT_DIRECTORY" -o "$GENERATED_PATH/Catalogs"
"$CURRENT_DIRECTORY/codegenutils/objc-identifierconstants" -f "$CURRENT_DIRECTORY/Classes" -o "$GENERATED_PATH/Identifiers" -u
"$CURRENT_DIRECTORY/codegenutils/objc-customfontlist" -s -f "$CURRENT_DIRECTORY" -o "$GENERATED_PATH/Fonts" -u

# Install Cocoapods
pod install


rm -f "$CURRENT_DIRECTORY/setup-structure"